/*
 * Provided by CSTI Consulting 
 * Following GNU LESSER GENERAL PUBLIC LICENSE
 * You may obtain more details at
 *
 * http://www.csticonsulting.com
 * Copyright (c) 2006-2010 Consultation CS-TI inc. 
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.salesmanager.central.entity.functions;

// Generated Aug 31, 2007 1:42:55 PM by Hibernate Tools 3.2.0.b9

import java.util.Date;

/**
 * CentralFunction generated by hbm2java
 */
public class CentralFunction implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7533457899893418451L;
	private int centralFunctionId;
	private String centralFunctionCode;
	private String centralGroupCode;
	private String centralFunctionDescription;
	private byte centralFunctionPosition;
	private boolean centralFunctionVisible;
	private String centralFunctionUrl;
	private boolean centralFunctionNew;
	private Date centralFunctionNewUntil;
	private Date lastModified;

	public CentralFunction() {
	}

	public CentralFunction(int centralFunctionId, String centralFunctionCode,
			String centralGroupCode, byte centralFunctionPosition,
			boolean centralFunctionVisible, boolean centralFunctionNew) {
		this.centralFunctionId = centralFunctionId;
		this.centralFunctionCode = centralFunctionCode;
		this.centralGroupCode = centralGroupCode;
		this.centralFunctionPosition = centralFunctionPosition;
		this.centralFunctionVisible = centralFunctionVisible;
		this.centralFunctionNew = centralFunctionNew;
	}

	public CentralFunction(int centralFunctionId, String centralFunctionCode,
			String centralGroupCode, String centralFunctionDescription,
			byte centralFunctionPosition, boolean centralFunctionVisible,
			String centralFunctionUrl, boolean centralFunctionNew,
			Date centralFunctionNewUntil, Date lastModified) {
		this.centralFunctionId = centralFunctionId;
		this.centralFunctionCode = centralFunctionCode;
		this.centralGroupCode = centralGroupCode;
		this.centralFunctionDescription = centralFunctionDescription;
		this.centralFunctionPosition = centralFunctionPosition;
		this.centralFunctionVisible = centralFunctionVisible;
		this.centralFunctionUrl = centralFunctionUrl;
		this.centralFunctionNew = centralFunctionNew;
		this.centralFunctionNewUntil = centralFunctionNewUntil;
		this.lastModified = lastModified;
	}

	public int getCentralFunctionId() {
		return this.centralFunctionId;
	}

	public void setCentralFunctionId(int centralFunctionId) {
		this.centralFunctionId = centralFunctionId;
	}

	public String getCentralFunctionCode() {
		return this.centralFunctionCode;
	}

	public void setCentralFunctionCode(String centralFunctionCode) {
		this.centralFunctionCode = centralFunctionCode;
	}

	public String getCentralGroupCode() {
		return this.centralGroupCode;
	}

	public void setCentralGroupCode(String centralGroupCode) {
		this.centralGroupCode = centralGroupCode;
	}

	public String getCentralFunctionDescription() {
		return this.centralFunctionDescription;
	}

	public void setCentralFunctionDescription(String centralFunctionDescription) {
		this.centralFunctionDescription = centralFunctionDescription;
	}

	public byte getCentralFunctionPosition() {
		return this.centralFunctionPosition;
	}

	public void setCentralFunctionPosition(byte centralFunctionPosition) {
		this.centralFunctionPosition = centralFunctionPosition;
	}

	public boolean isCentralFunctionVisible() {
		return this.centralFunctionVisible;
	}

	public void setCentralFunctionVisible(boolean centralFunctionVisible) {
		this.centralFunctionVisible = centralFunctionVisible;
	}

	public String getCentralFunctionUrl() {
		return this.centralFunctionUrl;
	}

	public void setCentralFunctionUrl(String centralFunctionUrl) {
		this.centralFunctionUrl = centralFunctionUrl;
	}

	public boolean isCentralFunctionNew() {
		return this.centralFunctionNew;
	}

	public void setCentralFunctionNew(boolean centralFunctionNew) {
		this.centralFunctionNew = centralFunctionNew;
	}

	public Date getCentralFunctionNewUntil() {
		return this.centralFunctionNewUntil;
	}

	public void setCentralFunctionNewUntil(Date centralFunctionNewUntil) {
		this.centralFunctionNewUntil = centralFunctionNewUntil;
	}

	public Date getLastModified() {
		return this.lastModified;
	}

	public void setLastModified(Date lastModified) {
		this.lastModified = lastModified;
	}

}
