# GitHub workflow for CAST Imaging rescan with self-hosted action runner

name: Rescan Application in CAST Imaging Console

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Manual trigger from Actions tab

jobs:
  rescan:
    runs-on: self-hosted  # Use the self-hosted runner instead of windows-latest

    steps:
      # Step 1: Checkout the repository to the default location
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Copy repository to the target directory
      - name: Copy repository to target directory
        run: |
          copy "C:\path\to\app_source_code" "C:\path\to\target_directory" /E /Y

      # Step 3: List the contents of the checked-out repository in the target directory
      - name: List directory contents of repository
        shell: cmd
        run: dir "C:\path\to\app_source_code"

      # Step 4: Set JAVA_HOME to local Java installation
      - name: Set JAVA_HOME environment variable
        run: |
          set JAVA_HOME="C:\Program Files\Java\jdk-11.0.15.1"  # Set the path to your local Java installation
          echo JAVA_HOME is set to %JAVA_HOME%

      # Step 5: Verify Java Version
      - name: Verify Java Version
        run: |
          "%JAVA_HOME%\bin\java.exe" -version  # Check the local Java version

      # Step 6: Rescan the application using CAST AIP CLI
      - name: Rescan Application
        run: |
          java -jar aip-console-tools-cli.jar add --apikey="<api_key_from_imaging_console>" -n "AppName" --server-url="http://localhost:8081" --no-clone -f "C:\path\to\app_source_code" --verbose=false --set-as-current=true --upload-application=true --process-imaging=true
